import { Inter } from 'next/font/google'
import './globals.css'
import { Navbar } from './components/UI/navbar/Navbar'
import { Footer } from './components/UI/footer/Footer'
import { Sidenav } from './components/UI/sidenav/Sidenav'

const inter = Inter({ subsets: ['latin'] })

export const Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-200`}>
        <main className='tablet:px-[60px]'>
          <Navbar />
          <Sidenav/>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
